spring:
  autoconfigure:
     # 排除 Druid 自动配置
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
      # 指定使用 Druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: mysql_1 # 设置默认的数据源或者数据源组，默认值为 master
      strict: true # 严格匹配数据源，默认false。设置为 true 未匹配到指定数据源时抛异常,false 使用默认数据源
      datasource:
        mysql_1:
          url: jdbc:mysql://127.0.0.1:3306/mybatis_plus_database_1?characterEncoding=utf8&autoReconnect=true&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        mysql_2:
          url: jdbc:mysql://127.0.0.1:3306/mybatis_plus_database_2?characterEncoding=utf8&autoReconnect=true&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j,config
      useGlobalDataSourceStat: true
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.clay.mybatis.bean
  # MyBatis-Plus 全局配置
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      table-prefix: t_
      table-underline: true
  # MyBatis 原生配置
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.clay.mybatis.dao: debug
