package com.clay.mybatis.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.name
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.id
     *
     * @return the value of t_department.id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.id
     *
     * @param id the value for t_department.id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.name
     *
     * @return the value of t_department.name
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.name
     *
     * @param name the value for t_department.name
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}