package com.clay.mybatis.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.last_name
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.gender
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.email
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.dept_id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.id
     *
     * @return the value of t_employee.id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.id
     *
     * @param id the value for t_employee.id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.last_name
     *
     * @return the value of t_employee.last_name
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.last_name
     *
     * @param lastName the value for t_employee.last_name
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.gender
     *
     * @return the value of t_employee.gender
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.gender
     *
     * @param gender the value for t_employee.gender
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.email
     *
     * @return the value of t_employee.email
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.email
     *
     * @param email the value for t_employee.email
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.dept_id
     *
     * @return the value of t_employee.dept_id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.dept_id
     *
     * @param deptId the value for t_employee.dept_id
     *
     * @mbg.generated Sun Aug 28 19:09:43 CST 2022
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}